export const GET_WEATHER_FOR_CITIES = 'GET_WEATHER_FOR_CITIES';
export const GET_WEATHER_FOR_CITIES_SUCCESS = 'GET_WEATHER_FOR_CITIES_SUCCESS';
export const GET_WEATHER_FOR_CITIES_ERROR = 'GET_WEATHER_FOR_CITIES_ERROR';
export const GET_FORECAST_FOR_CITY = 'GET_FORECAST_FOR_CITY';
export const GET_FORECAST_FOR_CITY_SUCCESS = 'GET_FORECAST_FOR_CITY_SUCCESS';
export const GET_FORECAST_FOR_CITY_ERROR = 'GET_FORECAST_FOR_CITY_SUCCESS_ERROR';
